stages:
  - build
  - notify

build-job:
  stage: build
  script:
    - echo "✅ Build completed for $CI_COMMIT_BRANCH"

email-notification:
  stage: notify
  image: alpine:latest
  before_script:
    - apk add --no-cache msmtp
    # Write a proper msmtp config with a real "default" account
    - |
      cat > /root/.msmtprc <<EOL
      account default
      host smtp.gmail.com
      port 587
      auth on
      user ${SMTP_USER}
      password ${SMTP_PASS}
      from ${SMTP_USER}
      tls on
      tls_starttls on
      EOL
    - chmod 600 /root/.msmtprc
  script:
    - 'echo -e "Subject: [GitLab CI/CD] Pipeline Notification\n\nPipeline ${CI_PIPELINE_ID} for project ${CI_PROJECT_NAME} on branch ${CI_COMMIT_BRANCH} finished with status: ${CI_JOB_STATUS}" | msmtp mohan4295work@gmail.com'
  rules:
    - when: always


